Repository Tc2r1/Hacktoberfest_Interview_App, pull requests merged in 2022-10, with the labels that each got.

#33 Add java questions
  CONTRIBUTERS.MD
  Languages/Java/questions.json
Labels: hacktoberfest-accepted

#34 Added a new question in DSA section.
  CONTRIBUTERS.MD
  Languages/DSA/questions.json
Labels: hacktoberfest-accepted

#32 Add Amandeep Singh to contributors list
  CONTRIBUTERS.MD
  Languages/Android/questions.json
Labels: hacktoberfest-accepted

#53 Adding DSA and DSA questions
  CONTRIBUTERS.MD
  CONTRIBUTERS.csv
  Languages/DSA/questions.json
  Languages/JS/questions.json
Labels: hacktoberfest-accepted

#51 Uploaded 3 questions
  CONTRIBUTERS.MD
  Languages/_COPYfolderFORaddedLANGUAGE/questions.json
Labels: hacktoberfest-accepted

#58 Add 3 questions to java
  CONTRIBUTERS.MD
  Languages/Java/questions.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest 2022

#79 Adding JS Questions
  CONTRIBUTERS.MD
  Languages/JS/questions.json
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2022, hacktoberfest2022

#89 My new changes
  Languages/Java/questions.json
Labels: hacktoberfest-accepted

#92 Added 3 Questions to JSON file
  Languages/Java/questions.json
Labels: hacktoberfest-accepted

#72 Added 3 questions in the DSA JSON file
  CONTRIBUTERS.MD
  Languages/DSA/questions.json
Labels: hacktoberfest-accepted

#84 added 3 more java questions
  Languages/Java/questions.json
Labels: hacktoberfest-accepted

#101 Added a Launcher Icon for UX enhancement
  Interview_Prep_App/sharedresources/src/main/ic_launcher-playstore.png
  Interview_Prep_App/sharedresources/src/main/res/drawable/ic_launcher_background.xml
  Interview_Prep_App/sharedresources/src/main/res/drawable/ic_launcher_foreground.xml
  Interview_Prep_App/sharedresources/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Interview_Prep_App/sharedresources/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Interview_Prep_App/sharedresources/src/main/res/mipmap-hdpi/ic_launcher.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-hdpi/ic_launcher.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-mdpi/ic_launcher.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-mdpi/ic_launcher.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xhdpi/ic_launcher.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Interview_Prep_App/sharedresources/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: hacktoberfest-accepted

#100 I added questions and corrected punctuation.
  Languages/Android/answers.json
Labels: hacktoberfest-accepted

#97 I have given answers
  CONTRIBUTERS.csv
  Languages/HTML5/answers.json
  Languages/HTML5/questions.json
Labels: hacktoberfest-accepted

#102 Added a splash screen for #61
  Interview_Prep_App/native_kotlin/base/build.gradle
  Interview_Prep_App/native_kotlin/base/src/main/AndroidManifest.xml
  Interview_Prep_App/native_kotlin/base/src/main/java/com/nudennie/interviewprepapp/ui/main/SplashScreenActivity.kt
  Interview_Prep_App/native_kotlin/base/src/main/res/layout/activity_splash_screen.xml
  Interview_Prep_App/sharedresources/src/main/res/drawable/android_study.png
Labels: hacktoberfest-accepted

#129 added comments to various files in kotlin folder
  Interview_Prep_App/native_kotlin/base/src/main/java/com/nudennie/interviewprepapp/controllers/AnswersController.kt
  Interview_Prep_App/native_kotlin/base/src/main/java/com/nudennie/interviewprepapp/controllers/QuestionsController.kt
  Interview_Prep_App/native_kotlin/base/src/main/java/com/nudennie/interviewprepapp/repositories/models/MultipleChoiceQuestion.kt
  Interview_Prep_App/native_kotlin/base/src/main/java/com/nudennie/interviewprepapp/repositories/models/response/Question.kt
  Interview_Prep_App/native_kotlin/base/src/main/java/com/nudennie/interviewprepapp/ui/questions/DialogFragment.kt
Labels: documentation, Kotlin, hacktoberfest-accepted

#96 "Added 3 questions to question.json file and updated contributors.md"
  CONTRIBUTERS.MD
  Languages/Android/questions.json
Labels: documentation, good first issue, hacktoberfest-accepted

#139 Added Splash Screen for #66
  Interview_Prep_App/native_java/javatemplate/build.gradle
  Interview_Prep_App/native_java/javatemplate/src/main/AndroidManifest.xml
  Interview_Prep_App/native_java/javatemplate/src/main/java/com/tc2r/javatemplate/ui/main/SplashScreenActivity.java
  Interview_Prep_App/native_java/javatemplate/src/main/res/layout/activity_splash_screen.xml
  Interview_Prep_App/sharedresources/src/main/res/values/themes.xml
Labels: enhancement, good first issue, hacktoberfest-accepted

#136 3 answers are added to answer.json file
  CONTRIBUTERS.MD
  Languages/Java/answers.json
Labels: hacktoberfest-accepted

#143 Added android questions to json
  CONTRIBUTERS.MD
  Languages/Android/questions.json
Labels: hacktoberfest-accepted

#144 Added Android answers
  Languages/Android/answers.json
  Languages/_COPYfolderFORaddedLANGUAGE/answers.json
Labels: invalid

#145 Added Splash Screen in kotlin retrofit
  Interview_Prep_App/native_kotlin/retrofit/build.gradle
  Interview_Prep_App/native_kotlin/retrofit/src/main/AndroidManifest.xml
  Interview_Prep_App/native_kotlin/retrofit/src/main/java/com/interviewprep/kotlinretrofit/ui/splash_screen/SplashScreenActivity.kt
  Interview_Prep_App/native_kotlin/retrofit/src/main/res/layout/activity_splash_screen.xml
  Interview_Prep_App/sharedresources/src/main/res/drawable/splash_screen_logo.png
Labels: hacktoberfest-accepted

#137 Added a new question
  Languages/Java/questions.json
Labels: Java, Android, hacktoberfest-accepted

#150 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, help wanted, good first issue, hacktoberfest-accepted, non-code

#151 Comments on Android Summit 2022 live #148
  and-summit-22-notes/and-summit-22-notes-androidlion48.md
Labels: documentation, Android, hacktoberfest-accepted, non-code

#134 3 new answers are added to Answers.json file
  CONTRIBUTERS.MD
  Languages/Android/answers.json
Labels: Android, hacktoberfest-accepted, HTML5

#152 Added Android Dev Summit 2022 notes
  and-summit-22-notes/and-summit-22-notes-mksiddiq.md
Labels: documentation, help wanted, good first issue, hacktoberfest-accepted, non-code

#154 App Version using View Binding
  Interview_Prep_App/native_kotlin/view_binding_/.gitignore
  Interview_Prep_App/native_kotlin/view_binding_/build.gradle
  Interview_Prep_App/native_kotlin/view_binding_/proguard-rules.pro
  Interview_Prep_App/native_kotlin/view_binding_/src/main/AndroidManifest.xml
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/network/OkHttpProvider.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/network/RetrofitBuilders.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/models/Answer.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/models/MultipleChoiceQuestion.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/models/Question.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/models/response/AnswersResponse.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/models/response/QuestionsResponse.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/tc2rgithubrepository/Tc2rGithubRepository.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/repository/tc2rgithubrepository/source/remote/Tc2rGithubService.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/ui/main/MainActivity.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/ui/questions/DialogFragment.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/ui/questions/QuestionFragment.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/ui/score/ScoreActivity.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/ui/splash_screen/SplashScreenActivity.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/java/com/interviewprep/kotlinretrofit/util/OnFragmentInteractionListener.kt
  Interview_Prep_App/native_kotlin/view_binding_/src/main/res/layout/activity_main.xml
  Interview_Prep_App/native_kotlin/view_binding_/src/main/res/layout/activity_score.xml
  Interview_Prep_App/native_kotlin/view_binding_/src/main/res/layout/activity_splash_screen.xml
  Interview_Prep_App/native_kotlin/view_binding_/src/main/res/layout/fragment_dialog.xml
  Interview_Prep_App/native_kotlin/view_binding_/src/main/res/layout/fragment_question.xml
  Interview_Prep_App/settings.gradle
Labels: enhancement, good first issue, Kotlin, Android, hacktoberfest-accepted

#98 add java questions - #93
  Languages/Java/questions.json
Labels: hacktoberfest-accepted

#128 HTML5_added
  Languages/HTML5/answers.html
  Languages/HTML5/questions.html
  Languages/Java/questions.json
Labels: enhancement, hacktoberfest-accepted, HTML5

#141 added five questions
  Languages/JS/questions.json
Labels: hacktoberfest-accepted

#153 SplashScreen that support for Android 12.
  Interview_Prep_App/native_kotlin/retrofit/build.gradle
  Interview_Prep_App/native_kotlin/retrofit/src/main/AndroidManifest.xml
  Interview_Prep_App/native_kotlin/retrofit/src/main/java/com/interviewprep/kotlinretrofit/ui/main/MainActivity.kt
  Interview_Prep_App/native_kotlin/retrofit/src/main/res/values/splash_theme.xml
Labels: good first issue, Kotlin, hacktoberfest-accepted

#158 Request calls for all supported quiz language in native-java-retrofit module
  Interview_Prep_App/native_java/retrofit/src/main/java/com/dreams/interviewprepapp/repositories/Tc2rGithubRepository.java
  Interview_Prep_App/native_java/retrofit/src/main/java/com/dreams/interviewprepapp/repositories/tc2rgithubrepository/source/remote/Tc2rGithubService.java
Labels: enhancement, hacktoberfest-accepted

#168 Updated documents project
  Android Summit 2022 Notes/README.md
  Cheat_Sheets/README.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#169 Create intellij_cheatsheet.md
  Cheat_Sheets/intellij_cheatsheet.md
Labels: documentation, good first issue, hacktoberfest, non-code

#167 Adds request calls for all quiz languages for native-kotlin-retrofit module
  Interview_Prep_App/native_kotlin/retrofit/src/main/java/com/interviewprep/kotlinretrofit/repository/tc2rgithubrepository/Tc2rGithubRepository.kt
  Interview_Prep_App/native_kotlin/retrofit/src/main/java/com/interviewprep/kotlinretrofit/repository/tc2rgithubrepository/source/remote/Tc2rGithubService.kt
Labels: good first issue, hacktoberfest, Android, hacktoberfest-accepted

#178 Add files via upload
  125139-happy-halloween.json
  125139-happy-halloween.mp4
  dlf10_d3FKLnw38j.lottie
Labels: documentation, help wanted, good first issue
